name: Merge to Int Branch

on:
  workflow_run:
    workflows: ["List Commits from Merged PRs"]
    types:
      - completed

jobs:
  merge_to_int:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Int Branch
      run: |
        git checkout -b Int
        git push origin Int

    - name: Identify Commits from Merged PRs
      run: |
        # Logic to identify commits from merged PRs with comment 'TESTED'
        # This could involve using a script or manual identification in the GUI

    - name: Apply Changes to Int Branch
      run: |
        # Logic to apply identified changes to the Int branch
        # This could involve using a script or manual actions in the GUI

    - name: Push Changes to Int Branch
      run: |
        git push origin Int

    - name: Create Pull Request
      run: |
        # Logic to create a pull request from Dev to Int
        # This could involve using a script or manual actions in the GUI
